# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8e8y6UduyL_AeycFCgeH6vfs0vOKwDP
"""

!pip install faiss-cpu sentence-transformers tree-sitter tree-sitter-python google-generativeai requests
!pip install -q google-genai

from google.colab import userdata
import os

os.environ["GROK_API_KEY"] = userdata.get("GROK_API_KEY")
os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")
# In your secrets / env setup cell, add this alias
os.environ["GROQ_API_KEY"] = os.environ["GROK_API_KEY"]

policies = [
    "Policy 1: All discount logic must be approved by a finance manager before deployment. Hardcoded discount rates are forbidden.",
    "Policy 2: No code may bypass the approval_workflow service. All state changes must go through the workflow engine.",
    "Policy 3: Customer PII data must never be accessed outside the CustomerDataService class.",
    "Policy 4: All marketing emails must route through the CommunicationsGateway and respect opt-out flags.",
    "Policy 5: Regional pricing and legal restrictions must be enforced using the RegionConfig module.",
    "Policy 6: Customer behavioral data must not be used for analytics without explicit consent flags being set.",
    "Policy 7: Only HR systems may access employee salary records. No direct DB queries on the employee table.",
    "Policy 8: SLA-bound operations must complete within defined time windows stored in sla_config.json.",
    "Policy 9: All financial transactions must be logged to the AuditLogger before and after execution.",
    "Policy 10: Third-party vendor SDKs must be listed in approved_vendors.json before use.",
]

import faiss
import numpy as np
from google import genai
from google.genai import types

client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

EMBED_MODEL = "models/gemini-embedding-2-preview"

def embed_texts(texts: list[str]) -> np.ndarray:
    embeddings = []
    for text in texts:
        response = client.models.embed_content(
            model=EMBED_MODEL,
            contents=text,
            config=types.EmbedContentConfig(task_type="RETRIEVAL_DOCUMENT")
        )
        embeddings.append(response.embeddings[0].values)
    return np.array(embeddings, dtype="float32")

def embed_query(text: str) -> np.ndarray:
    response = client.models.embed_content(
        model=EMBED_MODEL,
        contents=text,
        config=types.EmbedContentConfig(task_type="RETRIEVAL_QUERY")
    )
    return np.array(response.embeddings[0].values, dtype="float32").reshape(1, -1)

# Re-run the index build
print("⏳ Embedding policies...")
policy_embeddings = embed_texts(policies)

dimension = policy_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(policy_embeddings)

print(f"✅ FAISS index built — {index.ntotal} policies, dimension {dimension}")

import ast
import textwrap

def parse_code_chunks(source_code: str, filename="code.py") -> list[dict]:
    """Extract functions and classes as individual chunks using Python's AST."""
    chunks = []
    try:
        tree = ast.parse(source_code)
    except SyntaxError:
        # Fallback: treat whole file as one chunk
        return [{"name": filename, "code": source_code}]

    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            chunk_code = ast.get_source_segment(source_code, node)
            if chunk_code:
                chunks.append({
                    "name": node.name,
                    "type": type(node).__name__,
                    "code": textwrap.dedent(chunk_code)
                })
    return chunks if chunks else [{"name": filename, "code": source_code}]

import requests
import json

GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL   = "llama-3.3-70b-versatile"

def _groq_headers() -> dict:
    return {
        "Authorization": f"Bearer {os.environ['GROK_API_KEY']}",
        "Content-Type": "application/json"
    }

def summarize_with_grok(code_chunk: str) -> str:
    payload = {
        "model": GROQ_MODEL,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are a code analyst. Describe what this code does in 2-3 sentences, "
                    "focusing on business logic, data access, and external calls."
                )
            },
            {
                "role": "user",
                "content": f"```python\n{code_chunk}\n```"
            }
        ],
        "max_tokens": 200
    }

    response = requests.post(GROQ_API_URL, headers=_groq_headers(), json=payload)
    data = response.json()

    if "choices" not in data:
        print(f"❌ Groq summarize error: {data}")
        return f"Summary unavailable: {data.get('error', {}).get('message', str(data))}"

    return data["choices"][0]["message"]["content"].strip()


def audit_chunk_with_grok(
    chunk_name: str,
    code: str,
    summary: str,
    relevant_policies: list[str]
) -> dict:

    policy_text = "\n".join(f"- {p}" for p in relevant_policies)

    prompt = f"""You are a compliance auditor. Analyze the following code against the provided policies.

CODE CHUNK: {chunk_name}
```python
{code}
```

CODE SUMMARY: {summary}

RELEVANT POLICIES:
{policy_text}

Respond in JSON with this exact format:
{{
  "compliant": true or false,
  "violations": ["list of specific violations found, empty if none"],
  "explanation": "clear explanation of your reasoning",
  "severity": "none | low | medium | high | critical"
}}"""

    payload = {
        "model": GROQ_MODEL,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are a policy compliance auditor. "
                    "Always respond with valid JSON only. "
                    "No markdown, no text outside the JSON object."
                )
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        "max_tokens": 500
    }

    response = requests.post(GROQ_API_URL, headers=_groq_headers(), json=payload)
    data = response.json()

    if "choices" not in data:
        print(f"❌ Groq audit error: {data}")
        return {
            "compliant": False,
            "violations": ["API error"],
            "explanation": str(data),
            "severity": "unknown"
        }

    raw = data["choices"][0]["message"]["content"].strip()

    # Strip markdown fences if model wraps response in them
    clean = (
        raw
        .removeprefix("```json")
        .removeprefix("```")
        .removesuffix("```")
        .strip()
    )

    try:
        return json.loads(clean)
    except json.JSONDecodeError:
        print(f"⚠️  JSON parse failed for chunk '{chunk_name}'. Raw response:\n{raw}")
        return {
            "compliant": False,
            "violations": ["JSON parse error"],
            "explanation": raw,
            "severity": "unknown"
        }

print("✅ Groq functions defined")

def retrieve_relevant_policies(code_summary: str, top_k=3) -> list[str]:
    """Embed the code summary and find the most relevant policies."""
    query_embedding = embed_query(code_summary)  # ← uses the embed_query function we defined earlier
    distances, indices = index.search(query_embedding, top_k)
    return [policies[i] for i in indices[0] if i < len(policies)]

def audit_chunk_with_grok(
    chunk_name: str,
    code: str,
    summary: str,
    relevant_policies: list[str]
) -> dict:

    policy_text = "\n".join(f"- {p}" for p in relevant_policies)
    prompt = f"""You are a compliance auditor. Analyze the following code against the provided policies.

CODE CHUNK: {chunk_name}
```python
{code}
```

CODE SUMMARY: {summary}

RELEVANT POLICIES:
{policy_text}

Respond in JSON with this exact format:
{{
  "compliant": true or false,
  "violations": ["list of specific violations found, empty if none"],
  "explanation": "clear explanation of your reasoning",
  "severity": "none | low | medium | high | critical"
}}"""

    payload = {
        "model": "llama-3.3-70b-versatile",
        "messages": [
            {"role": "system", "content": "You are a policy compliance auditor. Always respond with valid JSON only. No markdown, no text outside the JSON object."},
            {"role": "user", "content": prompt}
        ],
        "max_tokens": 500
    }

    response = requests.post(
        "https://api.groq.com/openai/v1/chat/completions",
        headers={"Authorization": f"Bearer {os.environ['GROK_API_KEY']}", "Content-Type": "application/json"},
        json=payload
    )
    data = response.json()

    if "choices" not in data:
        print(f"❌ Groq audit error: {data}")
        return {"compliant": False, "violations": ["API error"], "explanation": str(data), "severity": "unknown"}

    raw = data["choices"][0]["message"]["content"].strip()
    clean = raw.removeprefix("```json").removeprefix("```").removesuffix("```").strip()

    try:
        return json.loads(clean)
    except json.JSONDecodeError:
        return {"compliant": False, "violations": ["JSON parse error"], "explanation": raw, "severity": "unknown"}

# Confirm correct version is loaded
import inspect
src = inspect.getsource(audit_chunk_with_grok)
assert "groq.com" in src, "❌ Wrong version still loaded!"
print("✅ Correct audit function loaded — using Groq")

def run_compliance_audit(source_code: str, filename="code.py") -> dict:
    print(f"\n🔍 Auditing: {filename}")
    chunks = parse_code_chunks(source_code, filename)
    print(f"   Found {len(chunks)} code chunks")

    report = {"file": filename, "chunks": [], "summary": {"total": 0, "violations": 0, "critical": 0}}

    for chunk in chunks:
        print(f"   → Analyzing: {chunk['name']}")

        summary = summarize_with_grok(chunk["code"])
        relevant_policies = retrieve_relevant_policies(summary)
        audit = audit_chunk_with_grok(chunk["name"], chunk["code"], summary, relevant_policies)

        chunk_report = {
            "name": chunk["name"],
            "summary": summary,
            "policies_checked": relevant_policies,
            "compliant": audit.get("compliant", False),
            "violations": audit.get("violations", []),
            "explanation": audit.get("explanation", ""),
            "severity": audit.get("severity", "none")
        }

        report["chunks"].append(chunk_report)
        report["summary"]["total"] += 1
        if not audit.get("compliant", True):
            report["summary"]["violations"] += 1
        if audit.get("severity") == "critical":
            report["summary"]["critical"] += 1

    return report


def print_report(report: dict):
    print("\n" + "="*60)
    print(f"📋 COMPLIANCE REPORT — {report['file']}")
    print("="*60)
    s = report["summary"]
    print(f"   Chunks analyzed : {s['total']}")
    print(f"   Violations found: {s['violations']}")
    print(f"   Critical issues : {s['critical']}")
    print()

    for chunk in report["chunks"]:
        status = "✅ COMPLIANT" if chunk["compliant"] else "❌ VIOLATION"
        sev = f"[{chunk['severity'].upper()}]" if not chunk["compliant"] else ""
        print(f"  {status} {sev} — {chunk['name']}")
        print(f"    Summary: {chunk['summary'][:120]}...")
        if chunk["violations"]:
            for v in chunk["violations"]:
                print(f"    ⚠️  {v}")
        print(f"    Reasoning: {chunk['explanation'][:200]}...")
        print()

sample_code = '''
import requests

DISCOUNT_RATE = 0.25  # hardcoded 25% discount

def apply_discount(order_id, amount):
    """Apply a flat discount without approval."""
    discounted = amount * (1 - DISCOUNT_RATE)
    db.execute(f"UPDATE orders SET total={discounted} WHERE id={order_id}")
    return discounted

def get_customer_emails():
    """Pull customer emails directly from DB for a marketing blast."""
    rows = db.execute("SELECT email, name FROM customers WHERE opted_in=1")
    send_bulk_email(rows, template="promo_blast")  # bypasses CommunicationsGateway

def process_payment(payment_id, amount):
    """Process payment without audit logging."""
    vendor_sdk = __import__("unlisted_payment_sdk")  # unapproved vendor
    vendor_sdk.charge(amount)
    db.execute("UPDATE payments SET status='done' WHERE id=?", payment_id)
'''

report = run_compliance_audit(sample_code, "billing_service.py")
print_report(report)

# Save the report as JSON for your demo
import json
with open("compliance_report.json", "w") as f:
    json.dump(report, f, indent=2)
print("✅ Report saved to compliance_report.json")

# Show which policies were retrieved for each chunk (proves RAG is working)
for chunk in report["chunks"]:
    print(f"\n📌 {chunk['name']}")
    for p in chunk["policies_checked"]:
        print(f"   retrieved → {p[:80]}...")